print("random area calculator\n")
import random
x1=random.randint(0,100)
x2=random.randint(0,100)
x3=random.randint(0,100)
#x4=random.randint(0,100)
y1=random.randint(0,100)
y2=random.randint(0,100)
y3=random.randint(0,100)
print("Point A Co-Ordinates are")
print("(x1,y1) =(",x1,y1,")")
print()
#print("y1= ",y1)
print("Point B Co-Ordinates are")
print("(x2,y2) =(",x2,y2,")")
print()
#print("y2= ",y2)
print("Point C Co-Ordinates are")
print("(x3,y3) =(",x3,y3,")")
area=(x1*(y2-y3)+x2*(y3-y1)+x3*(y1-y2))
print()
"""abs() is used since there can't be a negtive Area"""
print("Area of the triangle is\n",abs(area))
