import turtle
Turtle=turtle.Turtle()
# #turtle.pendowm()
# Turtle.fillcolor("gray")
# Turtle.begin_fill()
# Turtle.circle(100)
# Turtle.end_fill()
# Turtle.penup()
# turtle.exitonclick()
# turtle.goto(-25,50)
# turtle.pendowm()
# Turtle.hideTurtle()
# Turtle.write("Circle!")
